---
title: Walking with Grace
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    show_meta: false
    comments: false
    author: phlow
- scope:
    path: ''
    type: posts
  values:
    show_meta: true
    comments: false
    author: phlow
slogan: Walking with Grace
description: Walking with Grace - A charitable trust that supports the Neonatal unit
  at Stockton North Tees University Hospital
author: scottfeltham
url: http://www.walkingwithgrace.org.uk
baseurl: ''
gems:
- jekyll-paginate
improve_content: 
urlimg: http://www.walkingwithgrace.org.uk/images/
logo: rounded_corner_logo.png
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
permalink: "/:categories/:title/"
highlight: pygments
excerpt_separator: "<!--more-->"
include:
- ".htaccess"
exclude:
- ".sass-cache"
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- INSTALL.md
language: en
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  profile: false
  ignore:
    envs:
    - development
favicon-64x64: favicon-64x64.png
og_image: http://images.phlow.de/phlow/phlow_de-logo-512x.png
og_locale: en_EN
og_type: website
og_title: Walking with Grace
og_description: Walking with Grace - A charitable trust that supports the Neonatal
  unit at Stockton North Tees University Hospital
disqus_shortname: feelingresponsive
sass:
  sass_dir: _sass
  style: :compressed
google_analytics_tracking_id: UA-68945205-1
